export enum Action {
  SET_DEPARTURE = "SET_DEPARTURE",
  SET_ARRIVAL = "SET_ARRIVAL",
  SET_DISTANCE = "SET_DISTANCE",
  SET_PRICE = "SET_PRICE",
  ADD_TRIP = "ADD_TRIP",
  SIGN_IN = "SIGN_IN",
  SIGN_OUT = "SIGN_OUT",
}
